### ISSUE TITLE
Add status codes defined in RFC6585 [JIRA: RIAK-1676]

### ISSUE THREAD

**Issue by kuenishi** [webmachine/webmachine#242]
Just adding to `webmachine_error.erl` will work for CS, but even without this CS just works.
- https://github.com/basho/riak_cs/pull/1118
- http://tools.ietf.org/html/rfc6585

**Comment by Basho-JIRA** [comment]
Just adding to webmachine_error.erl will work for CS, but even without this CS just works.

basho/riak_cs#1118
http://tools.ietf.org/html/rfc6585 

***[posted via JIRA by Derek Somogyi]***

**Comment by beerriot** [comment]
So I've probably spent too long looking into this, but here's what I've found.

This is not a request to add new paths to the graph or `decision_core`. Any resource can use any response code it likes by returning `{halt, Code}`, and can even include a "phrase" with it via `{halt, {Code, Phrase}}`. That phrase will end up in the status line of the response. I think the request here is to add the codes and phrases from RFC 6585 to the `webmachine_error` module so that a resource doesn't have to use the second form to get the right phrase for them.

But I don't think that's actually a solution.

The `webmachine_error` module is only used to populate the "Reason" section of the error response _body_. It doesn't affect the status line. The status line is populated by either the custom `Phrase` from the halt, or from a call to `httpd_util:reason_phrase/1`.

So in one sense, this "already works". Except you have to write a custom error handler, because there is no way for the current error logger to access a custom phrase. Not only does the accessor function in the `wrq` module strip off the phrase, but the response code isn't event set in wrq until after the call to the error handler.

I have a [95% solution to fix the error handler](https://github.com/beerriot/webmachine/compare/main...error-codes), but it requires breaking the `render_error` API, by changing the first parameter from `Code :: integer()` to `CodeAndPhrase :: {Code :: integer(), Phrase :: string() | undefined}`. And after digging through all the code to be sure that was the necessary change, I have a small pile of additional changes I would make.

So I'm not opening a pull-request just yet. Commenting here in case anyone has thoughts.
