### ISSUE TITLE
500 error when browser lies about Content-Length

### ISSUE THREAD

**Issue by timclassic** [webmachine/webmachine#248]
IE8 has a habit of cleanly shutting down TCP connections in between the request headers and the request body of a POST when a page navigation occurs.  I see this behavior frequently when attempting to submit a POST in a window unload handler, but could theoretically happen with any page navigation.

(Chrome handles this differently; you either get the whole POST or none at all)

When this browser behavior occurs, Webmachine crashes with the following:

```
{error,{badmatch,{error,closed}},
       [{webmachine_request,recv_unchunked_body,3,
                            [{file,"src/webmachine_request.erl"},{line,489}]},
        {webmachine_request,do_recv_body,1,
                            [{file,"src/webmachine_request.erl"},{line,448}]},
        {webmachine_request,call,2,
                            [{file,"src/webmachine_request.erl"},{line,196}]},
        {wrq,req_body,1,[{file,"src/wrq.erl"},{line,118}]},
        {rest_service_util,rd_to_event_proplist,1,
                           [{file,"src/rest_service_util.erl"},{line,339}]},
        {rest_service_util,is_authorized,2,
                           [{file,"src/rest_service_util.erl"},{line,60}]},
        {webmachine_resource,resource_call,3,
                             [{file,"src/webmachine_resource.erl"},
                              {line,186}]},
        {webmachine_resource,do,3,
                             [{file,"src/webmachine_resource.erl"},
                              {line,142}]}]}
```

Is this something I should expect Webmachine to handle more gracefully?  Obviously it is a faulty HTTP request, but I don't believe it's a crashable offense, as it is just bad input from an external source.

Depending on the response to my question, I may attempt to patch this myself and submit a PR.  Is there any guidance on handling malformed requests in Webmachine?

**Comment by seancribbs** [comment]
@timclassic That's sort of a question of philosophy: is it better to let it crash or to return control to your code with an error tuple? While the error reporting can be improved, I worry that NOT crashing here would introduce subtle bugs.

A point you might want to consider -- why is your resource fetching the request body inside `is_authorized/2`? Can the request be authorized with headers alone?

**Comment by timclassic** [comment]
I think that (in this case) the fact that it crashes in `is_authorized/2` is just a detail.  The user happens to be authorized and we would go on to fetch the request body eventually anyway.  I will double-check this area to make sure it's not doing anything terribly weird.

Are you concerned about subtle bugs in Webmachine, or the code using Webmachine (or both)?

Either way, I will poke around in the code a bit more.  I want to see if Webmachine has a general mechanism for handling request processing errors.  Specifically, does it handle unexpected connection closure in other places?  Advice is welcome.

**Comment by seancribbs** [comment]
I'm concerned with subtle bugs in applications that result from Webmachine _not_ crashing/erroring/throwing in this instance. Honestly the decision flow should stop if the connection has closed because there's no one to reply to.

**Comment by seancribbs** [comment]
I guess my point is, crashing is the right answer here. How that crash is handled and reported is another discussion, but a worthy one.

**Comment by timclassic** [comment]
Ah, I think we may be on the same page, then.  When I said "crash" above I meant an unhandled error that bubbles up as a CRASH REPORT into SASL, looking very much like a bug.  I _think_ you are using "crash" to mean "stop whatever we're doing right now."  Please correct me if I read this wrong.

I agree 100% that control flow should stop immediately, since it is nonsense to continue.  In this case, I would rather _my_ code crash because it doesn't handle part of the interface to wrq:req_body/1 (a throw or error tuple) rather than crashing inside of Webmachine and trying to catch a badarg error in my code to keep these messages out of the SASL logs.

(I still haven't done any of the additional investigation I mentioned above.)

EDIT: It seems I'm still using "crash" to mean "unhandled runtime exception" :)

**Comment by beerriot** [comment]
I like the idea of exposing the read error to the resource, instead of failing internally on a `badmatch`. I think there are cases where a resource may want to continue processing, even though the response can't be delivered.

Although, there is a way to do this without modifying webmachine: wrap the resource's call to `wrq:req_body/1` in `try ... catch error:{badmatch, {error, closed}} -> ... end.`. You can do whatever you like in that catch clause. I think catching a `badmatch` is bad API, but it does work.

Also, even without the try-catch, request processing does not stop completely. Notably, `finish_request/2` is still called. So, if a resource had been doing something like streaming bytes to a file handle, as long as that handle is available (in the resource context, process dictionary, etc.), there is a chance to "do something" after the error.

For example, modifying [webmachine_demo_fs_resource.erl](https://github.com/webmachine/webmachine-demo/blob/master/src/webmachine_demo_fs_resource.erl) to wrap the `wrq:req_body/1` call and add a `finish_request/2` like so:

```erlang
accept_content(ReqData, Context) ->
    Path = wrq:disp_path(ReqData),
    FP = file_path(Context, Path),
    ok = filelib:ensure_dir(FP),
    ReqData1 = case file_exists(Context, Path) of
        {true, _} ->
            ReqData;
        _ ->
            LOC = "http://" ++
                   wrq:get_req_header("host", ReqData) ++
                   "/fs/" ++ Path,
            wrq:set_resp_header("Location", LOC, ReqData)
    end,
    try
        Value = wrq:req_body(ReqData1),
        case file:write_file(FP, Value) of
            ok ->
                {true, wrq:set_resp_body(Value, ReqData1), Context};
            Err ->
                {{error, Err}, ReqData1, Context}
        end
    catch error:{badmatch, {error, closed}} ->
            {{error, closed_early}, ReqData1,
             Context#context{metadata=[{error, closed}
                                      |Context#context.metadata]}}
    end.

finish_request(ReqData, Context) ->
    case proplists:is_defined(error, Context#context.metadata) of
        true ->
            Path = wrq:disp_path(ReqData),
            FP = file_path(Context, Path),
            ok = filelib:ensure_dir(FP),
            file:write_file(FP, "finished");
        false ->
            ok
    end,
    {ok, ReqData, Context}.
```

Means that a POST or PUT that doesn't send the whole body results in a file with the content "finished", and a line in the error log that is only:

```
[error] path=/fs/p {error,closed_early}
```

**Comment by beerriot** [comment]
After some thought and experimentation, it seemed like altering webmachine to `throw` instead of `badmatch` was a good resolution here. This retains the behavior of immediately shutting down the request if a resource doesn't catch it. But it also provides a stable API for the resource to handle the error itself if it does. I've updated the wiki to note that `req_body` and `stream_req_body` now throw `{webmachine_recv_error, Reason}` when encountering problems reading the body: https://github.com/webmachine/webmachine/wiki/Request-Data-API

**Comment by timclassic** [comment]
@beerriot, I no longer use Webmachine in any current projects, but it sounds like the implemented solution would have worked great my original problem. Thanks!
