### ISSUE TITLE
App env breaks option handling

### ISSUE THREAD

**Issue by zzantozz** [webmachine/webmachine#281]
According to the wiki, a custom error handler [can be installed via the `error_handler` option](https://github.com/webmachine/webmachine/wiki/Configuration#error-handler); however, a [commit from October](https://github.com/webmachine/webmachine/commit/a06256e0d3a2224e934157788a6a49d9346c7f18) added several ["default" values to the webmachine app file](https://github.com/webmachine/webmachine/commit/a06256e0d3a2224e934157788a6a49d9346c7f18#diff-0439e3c60075d41ff24ade175d2d1195R13). One of them is the `error_handler`, and the [option-handling code](https://github.rackspace.com/dcx/webmachine/blob/a06256e0d3a2224e934157788a6a49d9346c7f18/src/webmachine_mochiweb.erl#L64) only sets an option in the env if it's absent. Therefore, `error_handler` cannot be set as an option. This would also affect `rewrite_module`, as it's added to the app file as well.

**Comment by beerriot** [comment]
I think the right answer here is to update the wiki. Instead of passing config options to the Webmachine supervisor startup, they should be specified in the release's system config. For example, the rebar3 template will create a `config/sys.config` file, and adding to it like so will successfully set `error_handler`:

```erlang
[
   {'myapp', [ % stuff added by the template
                    ]},
   {'webmachine', [{error_handler, myapp_custom_error_handler}]}
].
```

I would be tempted in the future to also deprecate/remove the ability to pass these config options to the supervisor startup. I think they're mostly hanging around from days before easy release bundling.

**Comment by beerriot** [comment]
I've made the update to the wiki. Hope it helps. Thanks for reporting!
