### ISSUE TITLE
Is there a behavior for webmachine resources?

### ISSUE THREAD

**Issue by andreashasse** [webmachine/webmachine#311]
Hi,

I can not find a behavior for webmachine resources, even though it most likely would be very suitable for a behavior. Has this been up for discussion previously?

**Comment by beerriot** [comment]
Hi, Andreas. My memory is fuzzy, but I think there were a couple of attempts at a resource behavior long in the past. They never came into use, because they forced you to write one-off defaults for each callback you weren't interested in (or drown in warnings at compile). It made more sense for resources to omit callbacks they weren't interested in, and accept a default pre-defined in [`webmachine_resource.erl`](https://github.com/webmachine/webmachine/blob/master/src/webmachine_resource.erl#L50-L126).

Disclaimer: I haven't kept up with whether there are advancements in Erlang behaviours that would make it worthwhile today.

**Comment by seancribbs** [comment]
> I haven't kept up with whether there are advancements in Erlang behaviours that would make it worthwhile today.

Nowadays there's the `-optional_callback` attribute we could use for all the standard callbacks, but we still wouldn't be able to type body-producing functions.

**Comment by andreashasse** [comment]
Hi, thanks for your answers.
As Sean pointed out, the optional callback and being able to add types are great additions to behaviors in erlang. I haven't looked at what types can be used in this behavior, but I hope something better than `any()` :)?

I was looking for a callback because I'm working on a system where we use xref to find unused exports. As xref can not follow calls made from any erlang apply (and the like) and callbacks are typically called that way, we added a rule not to warn about unused exported functions that are part of implementing a behavior.

If the types that can be used aren't very strict, then maybe the behavior isn't so useful?
