### ISSUE TITLE
Make errors messages nicer for undefined handlers

### ISSUE THREAD

**Issue by mitchellh** [webmachine/webmachine#69]
Currently if a handler you specified is undefined, you get a HUGE error message. It looks a lot like this: https://gist.github.com/ca6b961cb39d0cd49f87

It would be nice if webmachine caught this error and gave a nicer error message (perhaps along with the huge stack trace, if someone finds that helpful), since it would certainly be easier especially when you're new to webmachine.

**Comment by beerriot** [comment]
This was fixed by #152 in commit f439563c2777db1b84dad603b64c987883b624fd. The huge error message was due to the `#wm_reqdata{}` being passed as an argument to the undefined function. That record nests `#wm_reqstate{}`, which nested `#wm_reqdata{}` and round and round. This was the reason for `wm_request:trim_state` and `wm_resource:trim_trace`, both of which can probably go away now.
